---
services:
  droplight:
    image: balintsoos/droplight
    build: .
    container_name: droplight
    volumes:
      - ./pb_data:/pb/pb_data
    ports:
      - "8090:8090"
    env_file: ".env"
    restart: unless-stopped
